<script lang="ts">
	import IsnadInput from '$lib/components/isnadInput.svelte';
	import { isnads } from '$lib/stores/globalStore';
	import { onMount } from 'svelte';
	import toast from 'svelte-french-toast';

	export let currentStep;

	onMount(async () => {
		console.log($isnads);
		console.log($isnads);
	});
</script>

<h3 class="text-2xl font-bold mt-5">Step 2</h3>

<p class="text-lg mt-2">
	Please review the extracted chains of narrators. Keep in mind that these chains are generated by
	an AI, which may introduce errors. You have the option to edit the chains by interacting with the
	schema. Once you are satisfied with the changes, click the button below to visualize the isnads.
</p>

<br />
<div class="flex flex-col h-full gap-y-4 overflow-auto">
	{#each $isnads as isnad}
		<section class="flex flex-col bg-[#a59cdb] rounded-lg text-black p-3">
			<h3 class="text-xl font-bold mb-2">Chain of transmission :</h3>

			<p class="arabic" dir="rtl">{isnad.text}</p>

			<br />
			<div class="flex flex-col">
				{#if isnad.transmitters.length === 0}
					<!-- Loading wheel -->
					<div class="flex gap-3 flex-col w-full items-center justify-center">
						<div class="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900"></div>

						<p class="text-base ml-2">
							Please wait while we reconstruct the chain of transmission...
						</p>
					</div>
				{:else}
					<h3 class="text-xl font-bold mb-2">Extracted Transmitters :</h3>

					<div class="flex flex-row flex-wrap gap-2">
						{#each isnad.transmitters as transmitter, i}
							<div class="flex items-center">
								<div class="flex flex-col items-center gap-x-2 bg-[#7e95d3] px-3 py-2 rounded-2xl">
									<p class="text-lg arabic">{transmitter.arabic_name}</p>
									<p class="text-sm">{transmitter.latin_name}</p>
								</div>

								{#if i !== isnad.transmitters.length - 1}
									<svg
										xmlns="http://www.w3.org/2000/svg"
										fill="none"
										viewBox="0 0 24 24"
										stroke-width="1.5"
										stroke="currentColor"
										class="size-5 ml-2"
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3"
										/>
									</svg>
								{/if}
							</div>
						{/each}
					</div>
				{/if}
			</div>
		</section>
	{/each}
</div>

<br />

<button
	class="mt-auto bg-[#471839] py-2 rounded-lg hover:bg-[#38132d] duration-100"
	on:click={() => {
		toast.success('Isnads visualized successfully!');
	}}
>
	Visualize Isnads
</button>
